# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Laxystem
email: the@laxla.quest
description: >-
  Website and blog of a plural system. Meowers gone rogue.
baseurl: "/"
url: "https://laxla.quest"
github_username: "Laxystem"
skin: "/assets/css/skins/dark.css"

remote_theme: "mmistakes/so-simple-theme@3.2.0"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-archives

google_fonts:
  - name: "Lora"
    weights: "400,400i,700,700i"
  - name: "JetBrains Mono"
    weights: "400,400i,700,700i"
  - name: "Alef"
    weights: "400,400i,700,700i"

defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: true
      author: Laxystem
      comments: false
  - scope:
      path: ""
    values:
        entries_layout: grid

author: Laxystem
category_archive_path: "/blog/"
tag_archive_path: "/blog/browse/tags/"
permalink: /blog/:categories/:year/:month/:day/:title

jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: autogenned-category
    tag: autogenned-tag
  permalinks:
    category: "/blog/:name.html"
    tag: "/blog/browse/tags/:name.html"

footer_links:
  - title: Feed
    url: feed.xml
    icon: fas fa-rss-square
  - title: GitHub
    url: https://GitHub.com/Laxystem/Laxystem
    icon: fas fa-github-square
  - title: Mastodon (English)
    url: https://tech.lgbt/@laxla
    icon: fa-brands fa-mastodon
  - title: Mastodon (Hebrew)
    url: https://tooot.im/@laxystem
    icon: fa-brands fa-mastodon
  - title: Sitemap
    url: sitemap.xml
    icon: fas fa-map

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .idea/
  - .run.bash
